import { Movie } from './types';

export const INITIAL_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Cuộc Chiến Trong Chúng Ta',
    originalTitle: 'Cuộc Chiến Trong Chúng Ta',
    description: 'An aspiring director hits rock bottom after 20 years chasing his debut — until he meets an overwhelmed producer who helps him rediscover his self-worth.',
    posterUrl: '/images/cuoc-chien-trong-chung-ta-thumb_11zon.jpg',
    backdropUrl: '/images/cuoc-chien-trong-chung-ta-poster.jpg',
    rating: 8.7,
    year: 2026,
    genres: ['Drama', 'Mentality'],
    duration: '2h 49m',
    status: 'completed',
    progress: 100,
    director: 'Cha Yeong-hun',
    cast: ['Go Youn-jung', 'Koo Kyo-hwan'],
  },
  {
    id: '2',
    title: 'Đại Chiến Vận Mệnh',
    originalTitle: 'Đại Chiến Vận Mệnh',
    description: 'Liệu số phận của chúng ta đã được định trước? Và liệu có ai thực sự có thể đọc được nó? Một cuộc thi đột phá dám tìm ra câu trả lời. 49 chuyên gia đọc vận mệnh hàng đầu Hàn Quốc – những bậc thầy về pháp sư, bói toán, bài tarot và xem tướng mặt – sẽ đặt danh dự của mình vào cuộc thi. Chỉ những người thực sự có thể đọc được vận mệnh mới sống sót. Ai sẽ là người chiến thắng?',
    posterUrl: '/images/dai-chien-van-menh-thumb_11zon.jpg',
    backdropUrl: '/images/dai-chien-van-menh-poster_11zon.jpg',
    rating: 8.8,
    year: 2025,
    genres: ['Horror', 'Thriller', 'Drama'],
    duration: '2h 46m',
    status: 'watching',
    progress: 45,
    director: '',
    cast: [],
  },
  {
    id: '3',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=2000',
    rating: 8.4,
    year: 2023,
    genres: ['Biography', 'Drama', 'History'],
    duration: '3h 00m',
    status: 'plan_to_watch',
    progress: 0,
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'],
  },
  {
    id: '4',
    title: 'Blade Runner 2049',
    originalTitle: 'Blade Runner 2049',
    description: 'A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.',
    posterUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&q=80&w=2000',
    rating: 8.0,
    year: 2017,
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    duration: '2h 44m',
    status: 'watching',
    progress: 75,
  },
  {
    id: '5',
    title: 'Inception',
    originalTitle: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=2000',
    rating: 8.8,
    year: 2010,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    duration: '2h 28m',
    status: 'completed',
    progress: 100,
  },
  {
    id: '6',
    title: 'The Batman',
    originalTitle: 'The Batman',
    description: 'Gotham cần một người trả lời cho những tội lỗi của gia đình Wayne. Một hành trình lột mặt nạ những bí mật gia đình gây sốc.',
    posterUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&q=80&w=2000',
    rating: 7.8,
    year: 2022,
    genres: ['Action', 'Crime', 'Drama'],
    duration: '2h 56m',
    status: 'plan_to_watch',
    progress: 0,
    director: 'Matt Reeves',
    cast: ['Robert Pattinson', 'Andy Serkis'],
    videoUrl: '/videos/BATMAN.mp4',
  },
  {
    id: '7',
    title: 'The Matrix',
    originalTitle: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=2000',
    rating: 8.7,
    year: 1999,
    genres: ['Action', 'Sci-Fi'],
    duration: '2h 16m',
    status: 'completed',
    progress: 100,
  },
  {
    id: '8',
    title: 'Avatar: The Way of Water',
    originalTitle: 'Avatar: The Way of Water',
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=2000',
    rating: 7.6,
    year: 2022,
    genres: ['Action', 'Adventure', 'Fantasy'],
    duration: '3h 12m',
    status: 'watching',
    progress: 30,
  },
  {
    id: '9',
    title: 'Spider-Man: Brand New Day',
    originalTitle: 'Spider-Man: Brand New Day',
    description: 'Tom Holland trở lại với vai Peter Parker trong một khởi đầu hoàn toàn mới.',
    posterUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&q=80&w=1000',
    backdropUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&q=80&w=2000',
    rating: 0, // Phim sắp chiếu chưa có rating
    year: 2025,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    duration: 'TBA',
    status: 'plan_to_watch',
    progress: 0,
    cast: ['Tom Holland'],
    videoUrl: '/videos/SPIDER-MAN.mp4',
  },
  {
    id: '10',
    title: 'Phí Phông: Quỷ Máu Rừng Thiêng',
    originalTitle: 'Phí Phông: Quỷ Máu Rừng Thiêng',
    description: 'Tại một ngôi làng mù sương chốn non cao, loài quỷ hút máu đã trở lại, gieo rắc nỗi kinh hoàng cho người dân.',
    posterUrl: '/images/phiphong.jpg',
    backdropUrl: '/images/phiphong.jpg',
    rating: 0,
    year: 2026,
    genres: ['Horror', 'Thriller', 'Drama'],
    duration: 'TBA',
    status: 'plan_to_watch',
    progress: 0,
    director: 'Đỗ Quốc Trung',
    cast: ['Kiều Minh Tuấn', 'Đoàn Minh Anh', 'Diệp Bảo Ngọc', 'NSƯT Hạnh Thúy', 'Nina Nutthacha Padovan'],
    videoUrl: '/videos/Phi-Phong.mp4', // Đã sửa lại đúng chữ hoa/chữ thường theo tên file của bạn
  },
  {
    id: '11',
    title: 'Tiếng Yêu Này Anh Dịch Được Không',
    originalTitle: 'Can This Love Be Translated',
    description: 'Đi khắp thế giới để quay chương trình truyền hình, cảm xúc của một người nổi tiếng và phiên dịch viên của cô lại chẳng thể nào thông dịch. Liệu tình yêu có tìm được ngôn ngữ riêng?',
    posterUrl: '/images/tieng-yeu-nay-anh-dich-duoc-khong-thumb.jpg',
    backdropUrl: '/images/anhbia_tiengyeunayanhdichduockhong.jpg',
    rating: 0,
    year: 2025,
    genres: ['Comedy', 'Drama', 'Romance'],
    duration: 'TBA',
    status: 'plan_to_watch',
    progress: 0,
    cast: ['Go Yoon-jung', 'Kim Sun-ho'],
    videoUrl: '/videos/tieng-yeu-nay-anh-dich-duoc-khong.mp4',
  },
  {
    id: '12',
    title: 'Huyền Thoại Lính Bếp',
    originalTitle: 'Legend of the Military Cook',
    description: 'Kang Seong Jae – một anh nuôi quân đội bình thường – bất ngờ nhận được "nhiệm vụ" trở thành huyền thoại nhà bếp trong quân doanh.',
    posterUrl: '/images/Huyen-Thoai-Linh-Bep-thumb.jpg',
    backdropUrl: '/images/bia_huyenthoailinhbep.jpg',
    rating: 0,
    year: 2025,
    genres: ['Comedy'],
    duration: 'TBA',
    status: 'plan_to_watch',
    progress: 0,
    cast: ['박지훈'],
    videoUrl: '/videos/huyen-thoai-linh-bep.mp4',
  }
];




export const GENRES = [
  'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime',
  'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror',
  'Music', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'
];

export const STATUS_OPTIONS = [
  { value: 'watching', label: 'Watching', color: 'bg-blue-500' },
  { value: 'completed', label: 'Completed', color: 'bg-green-500' },
  { value: 'on_hold', label: 'On Hold', color: 'bg-yellow-500' },
  { value: 'dropped', label: 'Dropped', color: 'bg-red-500' },
  { value: 'plan_to_watch', label: 'Plan to Watch', color: 'bg-zinc-500' }
];

export const THEME_COLORS = [
  '#3b82f6', // Blue
  '#8b5cf6', // Violet
  '#ec4899', // Pink
  '#ef4444', // Red
  '#f59e0b', // Amber
  '#10b981', // Emerald
];
